project:
  type: book

book:
  title: "Regression with R"
  author: "Niels Richard Hansen"
  date: "8/25/2025"
  site-url: "https://rwr.nrhstat.org"
  repo-url: "https://github.com/nielsrhansen/RwR"
  
  chapters:
    - index.qmd
    - 1_introduction.qmd
    - 2_linear.qmd
    - 3_birth.qmd
    - 4_regression.qmd
    - 5_exponential.qmd
    - 6_generalized_linear.qmd
    - references.qmd
  
reference-location: margin
citation-location: margin
bibliography: regression.bib

format:
  html:
    theme:
      - cosmo
      - brand
    code-block-bg: "#FCFCFC"
    code-fold: true

execute:
  cache: true


